### ISSUE TITLE
Include controlled vocabulary in Spanish for the element "basisOfRecord"

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#10]
The mapping of "basisOfRecord" element is not accepting the controlled vocabulary in Spanish, and because is a mandatory element with controlled vocabulary the publication is not allowed

![image](https://cloud.githubusercontent.com/assets/7827998/11006190/601dc5e8-8490-11e5-8021-e0ac671c4cf6.png)

**Comment by nestorjal** [comment]
GBIF/ipt issue.
