### ISSUE TITLE
Validation for e-mail when creating an user account 

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#17]
When  an account at the IPT is created, it should send an email notification and validation to check the e-mail, you can currently include any email account even if it doesn´t exist

![image](https://cloud.githubusercontent.com/assets/7827998/11008372/17ee97c6-849e-11e5-8900-13e052eb2314.png)

**Comment by danipilze** [comment]
To make it light, IPT doesn't have a SMTP server to send email, but a solution to this issue will be done with the new authentication system if the SIB Colombia.

**Comment by nestorjal** [comment]
GBIF/ipt issue.
