### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#19]
At the main page the user should be able to visualize the two possible options: Crear un Nuevo Recurso and Recuersos que puede administrar. I would suggest to either compress the section Crear un recurso or reorganize the page ex: Welcome to the IPT SiB Colombia...(Text) and then give them the two options: Crear un nuevo recurso / Recursos que puede administrar.

![image](https://cloud.githubusercontent.com/assets/13892476/11008806/f6a3b558-84a0-11e5-8b6b-6544eee154a5.png)

**Comment by nestorjal** [comment]
Fixed.
