### ISSUE TITLE
Missing datatables version value?

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/ipt#2]
dataTables.sInfo.versions

http://data.biodiversidad.co/sib-ipt-2.3.3-test/admin/organisations.do

![seleccion_046](https://cloud.githubusercontent.com/assets/3705866/10980568/b4ddfb22-83d0-11e5-999e-fd853da2792d.png)

**Comment by danipilze** [comment]
is it fixed?

**Comment by oscarduque018** [comment]
Does this refers to this table?
![image](https://cloud.githubusercontent.com/assets/4042071/13115666/adffa192-d566-11e5-99da-ce21da8ddb39.png)

**Comment by danipilze** [comment]
yes, but at the bottom
anyway, i can see it solve
