### ISSUE TITLE
Change in the automatic generation of the citation (section metadata - citations)

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#20]
The automatic generation of the field "¿Cómo referenciar este recurso?"  must have the publishing organization as author and not the resource contact 

![image](https://cloud.githubusercontent.com/assets/7827998/11008981/ef534286-84a1-11e5-9e35-678b6be882b7.png)

**Comment by danipilze** [comment]
@nestorjal agree?

**Comment by nestorjal** [comment]
Fixed in 2.3.3.
