### ISSUE TITLE
Próxima Publicación

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#21]
What is this column for?
Is it possible to add another one that contains the resource stage? Indexed, Updated, In process... 

![image](https://cloud.githubusercontent.com/assets/13892476/11008978/e69bf8ae-84a1-11e5-8a81-05fa4fccad2f.png)

**Comment by danipilze** [comment]
this is it for resources that are programmed to be published "every day", "every week", "every week".
we can hide "proxima publicación" column if you like

IPT is independent of indexation process, so he is not aware about it, maybe that information can be shown in the new dataportal
