### ISSUE TITLE
Delete buttons "seleccionar archivo" and "cargar" from the element "URL del logo del recurso" (section metadata: additional metadata)

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#22]
Delete these buttons because the user must search the Logo in a specific web page and not upload it 

![image](https://cloud.githubusercontent.com/assets/7827998/11009145/ff68c104-84a2-11e5-83e1-79ab592a5d74.png)

**Comment by danipilze** [comment]
@vdean26 do you know why?

**Comment by vdean26** [comment]
@danipilze perhaps that's how it used to work. It seems that the users tend to upload "unstandardized" images (in terms of size) and it often occupy more space in the server than expected. So how it works is that we ask the user to send the image, we standardize it and upload it to a web page and just copy de URL.

**Comment by nestorjal** [comment]
@cosmicgarden can we do it for 2.3.3?

**Comment by oscarduque018** [comment]
El IPT tendrá cambios mínimos de código
