### ISSUE TITLE
File type filter

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#23]
At the section Conjunto de Datos, when a user clicks "choose file" it should only appear a list with the type of files(text) allowed by the platform. 
eg: photo editing programs do not allow uploading excel files.

![image](https://cloud.githubusercontent.com/assets/13892476/11023505/9d7793e2-8648-11e5-9bdd-52519c51859c.png)

Additionally, the buttons are still in english. (Choose file and No file chosen)

**Comment by oscarduque018** [comment]
The button's text depends on browser language.
