### ISSUE TITLE
Missing translations in some sections

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#32]
In  sections like "Mapeo Darwin Core", "Translation page" there are missing translations in the definitions, also the errors appears in english 

![image](https://cloud.githubusercontent.com/assets/7827998/11035539/1e7345d6-86c1-11e5-80de-e76f98f6f7b7.png)

![image](https://cloud.githubusercontent.com/assets/7827998/11035618/74deb432-86c1-11e5-998e-5c4f46311327.png)

**Comment by danipilze** [comment]
@cosmicgarden may you please check what is it?

**Comment by nestorjal** [comment]
@cosmicgarden please check if the properties file has this translation, otherwise close this issue.

**Comment by oscarduque018** [comment]
"The error setting" text is a part of Struts framework, in the code. The text in the blue box is from the description of the extension of the DwC.
