### ISSUE TITLE
DarwinCore element in CAPITAL LETTERS

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#33]
In the "Translation page", the DarwinCore element appears in Capital Letters

![image](https://cloud.githubusercontent.com/assets/7827998/11035681/f0f32fb2-86c1-11e5-9e4f-1120540a9a5e.png)

**Comment by oscarduque018** [comment]
Los subtitulos h2, por diseño en el IPT están en mayúscula. Habría que hacer un estilo para este título en particular.
