### ISSUE TITLE
The extensions don't appear at the darwin core mappings section

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#34]
When installing the extension "Darwin Core measurement or facts" it doesn´t appear in the select box of "mapeo Darwin core" section

![image](https://cloud.githubusercontent.com/assets/7827998/11036146/b3d5c5ce-86c4-11e5-9de5-6a455c50b673.png)

![image](https://cloud.githubusercontent.com/assets/7827998/11036175/de8a00c8-86c4-11e5-9c50-1d267815e487.png)

**Comment by danipilze** [comment]
@cosmicgarden may you please check this?

**Comment by oscarduque018** [comment]
Solved in newest version
![image](https://cloud.githubusercontent.com/assets/4042071/13114888/7e9d988a-d563-11e5-8958-003a97fd34c1.png)
