### ISSUE TITLE
Translated data

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#41]
When one translates the data into the controlled vocabulary during the data mapping, in the "muestra de los datos" section it should appear the new sample version once the translation has been executed.

![image](https://cloud.githubusercontent.com/assets/13892476/11044776/dac0dd0e-86f1-11e5-9c7c-06ac6189ca24.png)

**Comment by danipilze** [comment]
may you please check if this is solve it?

**Comment by nestorjal** [comment]
Fixed.
