### ISSUE TITLE
Hide footer-bottom for non-sib IPT styles

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/ipt#44]
on footer-bottom is the sib logo and address
but for the non-sib IPT styles (green, yellow...)
this is not correct since it is meant to other institutions

**Comment by nestorjal** [comment]
@cosmicgarden can you check this out? probably the best way is to delete the logo from SiB's IPT but better to have a word from @javiesgm.

**Comment by oscarduque018** [comment]
By decision, all IPT´s will have the same styles and most of the images. In my opinion, the only difference will be the logo of the institution. I don't sure if the image in the footer gonna is changed. Please, talk about this with @javiesgm

**Comment by nestorjal** [comment]
Thanks, I'll close the issue since that supposedly isn't a priority.
