### ISSUE TITLE
Past version design in the main page table when using a filter

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#47]
Ghost of the past version designe when arranging the table though the organizing arrows. When using the organizing arrows in the main menu to arrange the resources available, one gets the column that has been reorganized highlighted in the colors of the past version of the IPT. 

In the image the column "Organizaciones" was reorganized.

![image](https://cloud.githubusercontent.com/assets/13892476/13820753/abe58748-eb6c-11e5-962f-a40c355c4ba8.png)

**Comment by nestorjal** [comment]
Will be fixed in 2.3.3.
