### ISSUE TITLE
Problem requesting DOI Number due to lack of Role information

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#48]
browser: firefox
 In order to request a DOI number, the Associated Parties (Metadata section) **must** have a role, but this information does not appear as mandatory(*) in the section. 
![image](https://cloud.githubusercontent.com/assets/13892476/14082574/682c25a2-f4d6-11e5-9879-132e52c1036d.png)

**Comment by nestorjal** [comment]
GBIF/ipt issue.
