### ISSUE TITLE
Problem with Default translation in Darwin Core Mapping

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#49]
When entering to the section Darwin Core Mapping to edit and translate the basisOfRecord element, it seems like the translation has been configured by default but after saving the translation, apparently the data that appears for default is not being processed and is not really being saved. In order to get the translation saved one has to click the reload button and rewrite the translation, which means that the default values are not being useful and instead, are confusing the users.

**Comment by nestorjal** [comment]
GBIF/ipt issue.
