### ISSUE TITLE
Error message when performing any action

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#5]
When performing any action like "creating a resource", "deleting a resource", "editing metadata", etc, an error message appears at the begging of the page 

![image](https://cloud.githubusercontent.com/assets/7827998/11002833/1c17d5f4-847d-11e5-96f5-784dd294bac4.png)

**Comment by mardeles** [comment]
Other error message when uploading a resource 

![image](https://cloud.githubusercontent.com/assets/7827998/11003026/58e53598-847e-11e5-96a3-3203d83a3c27.png)

**Comment by danipilze** [comment]
I think is because the IPT is installed in test/debug mode, @cosmicgarden may you please check it?

**Comment by oscarduque018** [comment]
In addition is necessary to change struts.properties
