### ISSUE TITLE
FreeMarker template error

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#50]
browser: firefox

The following error appears and doesn´t allow the publication of the resource: Colección de Reptiles - Museo de Herpetología de la Universidad de Antioquia. http://data.biodiversidad.co/sibresource.do?r=coleccion_mhua

![image](https://cloud.githubusercontent.com/assets/13892476/14255302/fe423266-fa58-11e5-846a-41f2628e073c.png)

**Comment by nestorjal** [comment]
Fixed.
