### ISSUE TITLE
Untranslated controlled vocabulary in basisOfRecord element

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#52]
During the migration to the new IPT 2.3.3 version we have encountered several improvements. However, through the upgrade some basic functions have become an obstacle not only for the non english speaking users but for some english speaking ones. Through the testing of the attached files we found that the controlled vocabulary for the basisOfRecord element in Spanish,Portuguese, Japanese and english are not being recognized by the mapping tool. The only data that is being recognized is the one that is in english but lacks the spaces between words (eg: basisOfRecrdENGLISHgood.txt).  Therefore, in order to upgrade the resources and allow the user to make the most of the new improvements of the tool, we have been forced to move back and out of the "normal" working process and proceed with the manual translation of this terms. 

[basisOfRecordENGLISHgood.txt](https://github.com/SIB-Colombia/ipt/files/219518/basisOfRecordENGLISHgood.txt)

[basisOfRecordENGLISH.txt](https://github.com/SIB-Colombia/ipt/files/219506/basisOfRecordENGLISH.txt)
[basisOfRecordESPANOL.txt](https://github.com/SIB-
[basisOfRecordENGLISHgood.txt]%28https://github.com/SIB-Colombia/ipt/files/219517/basisOfRecordENGLISHgood.txt%29
Colombia/ipt/files/219507/basisOfRecordESPANOL.txt)
[basisOfRecordPORTUGUES.txt](https://github.com/SIB-Colombia/ipt/files/219508/basisOfRecordPORTUGUES.txt)
[basisOfRecordJAPONES.txt](https://github.com/SIB-Colombia/ipt/files/219509/basisOfRecordJAPONES.txt)

**Comment by nestorjal** [comment]
GBIF/ipt issue.
