### ISSUE TITLE
Password recovery 

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#55]
When you enter the wrong password to the IPT, the following alert appears: 
![image](https://cloud.githubusercontent.com/assets/13892476/20350118/8551319c-abdb-11e6-9396-b11c0cc52c48.png)
It shows the option to send a message to the IPT Admin in order to recover the password and the email that appears is Daniel Amariles´s. Is there a way to change this email? or is it possible to have a button that allows the user to recover the password easily.

**Comment by nestorjal** [comment]
Please check this for 2.3.3.

**Comment by oscarduque018** [comment]
done
