### ISSUE TITLE
Delete resource in Home table

### ISSUE THREAD

**Issue by nestorjal** [SIB-Colombia/ipt#56]
The resource http://ipt.biodiversidad.co/sib/resource?r=reggeorprimates was deleted but remains in the home page, please remove it from the table.

**Comment by oscarduque018** [comment]
This is the reason why is not possible delete the resource. If is necessary, I'll delete the files in the datadir, to completely delete the resource.
![image](https://cloud.githubusercontent.com/assets/4042071/23069807/ca006c7c-f4f6-11e6-9208-a48749a9edaf.png)

**Comment by nestorjal** [comment]
@cosmicgarden. yes, please do that.

**Comment by oscarduque018** [comment]
Done
