### ISSUE TITLE
IPT update

### ISSUE THREAD

**Issue by nestorjal** [SIB-Colombia/ipt#57]
@valegrajales @cosmicgarden 

Our IPT is based on version **2.3.3-r01** but the latest version is **2.3.3-rdb4ab13**, GBIF/ipt issues [#1319](https://github.com/gbif/ipt/issues/1319#issuecomment-280310595) and [#1323](https://github.com/gbif/ipt/issues/1323#issuecomment-282297714) bring up the warning about the use of this non-officially released versions in production, therefore our IPT's must be updated.

**Comment by oscarduque018** [comment]
done, https://github.com/SIB-Colombia/ipt/issues/60
