### ISSUE TITLE
Consultar versión de IPTs a instalar en Sprint 1

### ISSUE THREAD

**Issue by valegrajales** [SIB-Colombia/ipt#59]
Preguntar a Kyle por los datos de la última versión de IPTs que reparan los issues sobre los cuales consultó Nestor.

**Comment by valegrajales** [comment]
Criterio de aceptación: Poner como comentario la versión de IPT que corrige los problemas (según Kyle) e indicar la URL de donde puede ser descargada dicha versión.

**Comment by oscarduque018** [comment]
A la consulta, está fué la respuesta
![image](https://cloud.githubusercontent.com/assets/4042071/23723827/98f90e6e-0418-11e7-9588-d6656c7808c9.png)

Las versiones de los releases se encuentran aquí, incluida la ipt-2.3.3, que es la que corresponde con el war en el repositorio de GBIF
https://github.com/gbif/ipt/releases/tag/ipt-2.3.3

**Comment by valegrajales** [comment]
Version of the installed release: IPT Versión 2.3.4-r68469e8
