### ISSUE TITLE
Make mandatory the fields of the metadata sections "Geographic coverage", "Taxonomic coverage", "Temporal coverage", "Samplig methods" and "Citations"

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/ipt#6]
At present only the basic metadata are mandatory and the resource can be published with few information, it is recommended that other fields are required for the completeness of the resources

**Comment by danipilze** [comment]
@nestorjal agree?

**Comment by nestorjal** [comment]
Fixed in 2.3.3
