### ISSUE TITLE
Actualizar IPTs

### ISSUE THREAD

**Issue by valegrajales** [SIB-Colombia/ipt#60]
Actualizar todos los IPTs que no tiene cambios de código a la versión indicada por Kyle. No olvidar hacer copia de respaldo previamente.

**Comment by valegrajales** [comment]
Criterio de aceptación: Listar la URL de cada uno de los IPTs actualizados, de modo que se pueda verificar en el "about" que la versión corresponda con la que se actualizó.

**Comment by oscarduque018** [comment]
Ya está para pruebas, la versión recomendada por Kyle, en http://ipt.biodiversidad.co/sib/, por favor @nestorjal verficar si continuan los problemas
