### ISSUE TITLE
Incorporar estilos de diseño y logos

### ISSUE THREAD

**Issue by valegrajales** [SIB-Colombia/ipt#61]
Incorporar los estilos de diseño y logos a los IPTs actualizados que serán instalados en el Sprint 1.

**Comment by valegrajales** [comment]
Criterio de aceptación: Se realiza una revisión visual por parte de product owner y stakeholders para verificar los estilos y logos estén presentes en la nueva versión de IPTs.

**Comment by oscarduque018** [comment]
Se realizó un cambio en el footer.ftl, respecto a la versión de GBIF para incluir el logo del SiB 
ad109401908cc6fa24a96f042a2c8cf3d39b43bd

**Comment by oscarduque018** [comment]
Se cambió estilos de acuerdo al css especificado 6ae8b457c97fcbe1b8aeccbbe3f7940a2f4a479c
