### ISSUE TITLE
Cambiar correo electrónico de contacto

### ISSUE THREAD

**Issue by valegrajales** [SIB-Colombia/ipt#62]
Como usuario de IPT necesito poder contactar al usuario administrador para solicitar cambio de contraseña. Para cumplir este issue es necesario cambiar el correo electrónico de contacto para realizar esta tarea administrativa. El correo de contacto es: sib@humboldt.org.co

**Comment by valegrajales** [comment]
Criterio de aceptación: Se debe verificar que en todos los IPTs el correo de contacto sea sib@humboldt.org.co

**Comment by dannyvelezv** [comment]
Criterio de aceptación: Se debe verificar que en todos los IPTs el correo de contacto sea sib@humboldt.org.co excepto para el IPT IAvH en donde el contacto debe ser i2d@humboldt.org.co

**Comment by nestorjal** [comment]
@dannyvelezv @valegrajales 

**Para el futuro:**
Teniendo en cuenta que hay 10 [instalaciones adicionales](https://sites.google.com/humboldt.org.co/wikisib/publicar/herramienta-de-publicaci%C3%B3n)  a las dos mencionadas, lo ideal sería que para cada una se contactara al administrador y este realmente cumpliera su rol, de no ser así sería una razón más para (como se habia dicho el año pasado) empezar a reducir el número de IPTs que tenemos, facilitando el trabajo para los dos enfoques involucrados.

**Comment by oscarduque018** [comment]
Ya se hizo el cambio en http://ipt.biodiversidad.co/sib/ por favor @nestorjal verificar si es correcto.

**Comment by oscarduque018** [comment]
Se realizaron los cambios del usuario admistrador principal en los IPT´s. Por indicaciones de @dannyvelezv en los IPT's con correo institucional presente, no se realizó el cambio, pero, los dejo indicados a continuación.
- http://ipt.sibcolombia.net/cr-sib/login.do No aplica, contraseñas asignadas manualmente
- http://ipt.biodiversidad.co/sib &#9745; sib@humboldt.org.co
- http://ipt.biodiversidad.co/biota Administrador de la revista biotacol@humboldt.org.co
- http://ipt.biodiversidad.co/iavh/ &#9745; i2d@humboldt.org.co
- http://ipt.biodiversidad.co/iiap Administrador de la institución jlloreda@iiap.org.co
- http://ipt.biodiversidad.co/resnatur/ &#9745; sib@humboldt.org.co
- http://ipt.biodiversidad.co/rnjb/ &#9745; sib@humboldt.org.co
- http://ipt.biodiversidad.co/rnoa/ &#9745; sib@humboldt.org.co
- http://ipt.biodiversidad.co/ambientebogota &#9745; sib@humboldt.org.co
- http://ipt.biodiversidad.co/sinchi/ Administrador de la institución ssua@sinchi.org.co
- http://ipt.biodiversidad.co/sirap-ec/ Administrador de la institución crios@wcs.org
- http://ipt.biodiversidad.co/invemar Administrador de la institución julio.bohorquez@invemar.org.co
- http://ipt.biodiversidad.co/valle/ Administrador de la institución patricia.chacon@correounivalle.edu.co
