### ISSUE TITLE
IPT-Putumayo

### ISSUE THREAD

**Issue by moreno7502** [SIB-Colombia/ipt#66]
Biodiversidad SiBCOlombia del departamento del Putumayo

**Comment by ghost** [comment]
Estimado usuario,

Este canal se encuentra habilitado solo para el reporte de errores en la herramienta IPT. Te invitamos a consultar nuestro portal de datos [datos.biodiversidad.co](http://datos.biodiversidad.co/) y filtrar o descargar los datos publicados a través del SiB Colombia para el departamento del Putumayo. Cualquier duda adicional agradecemos visites la página www.sibcolombia.net o escribirnos a sib@humboldt.org.co

Cordial saludo,
