### ISSUE TITLE
"Solicitar nueva característica" option at the bottom of the page

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#7]
The button "Request new feature" at the bottom of the page leads the user to GBIF´s github instead of SiB´s github.

![image](https://cloud.githubusercontent.com/assets/13892476/11006620/a9664764-8492-11e5-960a-683431771a86.png)

**Comment by vdean26** [comment]
The option "Request new feature" https://cloud.githubusercontent.com/assets/13892476/11006232/9dd2ef12-8490-11e5-9b27-4afb60c39916.png)
 the main

**Comment by danipilze** [comment]
I think it should go to the SIB CRM, when we have it established.

**Comment by nestorjal** [comment]
Fixed
