### ISSUE TITLE
Muestra de los datos at the de Mapeo DwC Section 

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#8]
"Muestra de los datos" at the Mapeo de los datos section is unclear. I wolud suggest to put just one column with 3-4 inputs from the source file. We should try to make it look like the original source so the user can make the connection between what he is seeing on the IPT page and what he has in the source file.  We can also try to make the title more explicit  like: "Muestra de sus datos" or "Ejemplo de sus datos" or "Así se ve este elemento en sus datos".

![image](https://cloud.githubusercontent.com/assets/13892476/11007818/84c778d0-849a-11e5-85a8-82d8108d41c3.png)

**Comment by nestorjal** [comment]
The issue remains but will be closed until we round off 2.3.3 version.
