### ISSUE TITLE
Filtro feature

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/ipt#9]
The option "Filtro" Mapeo de la fuente de datos section is rather confusing. I consider that this feature can be satisfied through the text editors.
This feature is not relevant in our publication scheme, where the data upload is only allowed after it has gone though the standardization process.

**Comment by danipilze** [comment]
@vdean26 may you please enlighten us with a print screen?

**Comment by vdean26** [comment]
@danipilze
![image](https://cloud.githubusercontent.com/assets/13892476/12331026/cec8e490-bab5-11e5-9933-8c7be48641a3.png)

**Comment by nestorjal** [comment]
Definition isn't clear but the feature is truly useful, I'll create a new issue in order to improve that definition.
